apiVersion: v1
kind: Endpoints
metadata:
  name: cockpit 
  namespace: kube-system
subsets:
- addresses:
  # list all external ips for this service
  - ip: <insert-master-ip>
  ports:
  - name: cockpit 
    port: 9090 
    protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: cockpit 
  namespace: kube-system
spec:
  ports:
  - name: cockpit
    protocol: TCP
    port: 9090 
    targetPort: 9090 
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cockpit-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    #traefik.frontend.rule.type: PathPrefixStrip
    traefik.frontend.redirect.entryPoint: https
spec:
  rules:
  - host: admin.<insert-fqdn>
    http:
      paths:
      - path: /
        backend:
          serviceName: cockpit
          servicePort: 9090
